force-app/main/default/objects/Stock_Data__c/Stock_Data__c.object-meta.xml
<CustomObject>
    <label>Stock_Data</label>
    <nameField>
        <label>Stock Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stock_Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Data__c/fields/Close_Price__c.field-meta.xml
<CustomField>
    <fullName>Close_Price__c</fullName>
    <label>Close Price</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Stock_Data__c/fields/Open_Price__c.field-meta.xml
<CustomField>
    <fullName>Open_Price__c</fullName>
    <label>Open Price</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Stock_Data__c/fields/Ticker_Symbol__c.field-meta.xml
<CustomField>
    <fullName>Ticker_Symbol__c</fullName>
    <label>Ticker Symbol</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AAPL</fullName>
            </value>
            <value>
                <fullName>NCR</fullName>
            </value>
            <value>
                <fullName>CRM</fullName>
            </value>
            <value>
                <fullName>MSFT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/YahooFinanceScrapingTests.cls
@isTest
public with sharing class YahooFinanceScrapingTests {
   

    @TestSetup
    static void makeData(){

        Stock_Data__c sd = new Stock_Data__c();

        sd.Name = 'AAPL 2023-06-22';
        sd.Ticker_Symbol__c = 'AAPL';
        sd.Date__c = Date.newInstance(2023, 06, 22);

        insert sd;
    }

    @isTest
    static void testScrapeHTML(){

        String ticker = 'AAPL';

        String givenDateMiliseconds = getTimeInMiliseconds(22, 06, 2023);
        String givenDatePlusOneDayMiliseconds = getTimeInMiliseconds(22, 06, 2023);

        Test.startTest();

        Test.setMock(HttpCalloutMock.class, new YahooFinanceScrapingMock());

        YahooFinanceScraping.YahooFinanceHTMLWrapper yfw = YahooFinanceScraping.scrapeHTML(ticker,givenDateMiliseconds,givenDatePlusOneDayMiliseconds);

        Test.stopTest();

        String expectedValue = '<html></html>';

        System.assertEquals(yfw.ticker, ticker);
        System.assertEquals(expectedValue, yfw.stockData);
        System.assertEquals(expectedValue, yfw.companyInfo);
        System.assertEquals(expectedValue, yfw.marketCap);
    }

    @isTest
    static void testVerifyDuplicates(){
        String ticker = 'AAPL';

        List<Stock_Data__c> duplicateTickers = YahooFinanceScraping.verifyDuplicates(new List<String>{ticker}, '2023-06-22');

        System.assertEquals(1, duplicateTickers.size());
    }

    @isTest
    static void testAddInsertResultsToWrapper(){

        Stock_Data__c data = new Stock_Data__c();

        data.Ticker_Symbol__c = 'AAPL';
        data.Open_Price__c = 1;
        data.Close_Price__c = 1;
        data.Date__c = Date.today();
        
        List<Database.SaveResult> results = Database.insert(new List<Stock_Data__c>{data});


        YahooFinanceScraping.YahooLWCResponse response = new YahooFinanceScraping.YahooLWCResponse();
        response.ticker = 'AAPL';

        List<YahooFinanceScraping.YahooLWCResponse> responses = new List<YahooFinanceScraping.YahooLWCResponse>{response};
        
        List<YahooFinanceScraping.YahooLWCResponse> returnList = YahooFinanceScraping.addInsertResultsToWrapper(results, responses);

        System.assertEquals(1, returnList.size(),'returnList should have 1 member');
        YahooFinanceScraping.YahooLWCResponse returnResponse = returnList[0];

        System.assertEquals(true, returnResponse.success);

    }
    
    static String getTimeInMiliseconds(Integer day, Integer month, Integer year){

        DateTime givenDate = DateTime.newInstance(year, month, day);
        Long givenDateMilisecondsLong = givenDate.getTime();

        return String.valueOf(givenDateMilisecondsLong);
    }

}